"""empty message

Revision ID: e2931ab74f3e
Revises:
Create Date: 2026-10-01 14:37:45.180957

"""

from typing import Sequence, Union

# revision identifiers, used by Alembic.
revision: str = "e2931ab74f3e"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
